from __future__ import annotations

"""Class catalog and business mapping used by the sorting module."""

CLASS_NAMES = [
    "Aerosols",
    "Tin",
    "Cardboard",
    "Cellulose",
    "Ceramic",
    "Combined plastic",
    "Container for household chemicals",
    "Disposable tableware",
    "Electronics",
    "Foil",
    "Furniture",
    "Glass bottle",
    "Liquid",
    "Milk bottle",
    "Organic",
    "Paper bag",
    "Paper",
    "Plastic bag",
    "Plastic bottle",
    "Plastic cup",
    "Plastic toys",
    "Printing industry",
    "Scrap metal",
    "Stretch film",
    "Tetra pack",
    "Textile",
    "Ramen Cup",
    "Food Packet",
]

# yellow: recyclable (french yellow bin), glass: glass-only bin, other: residual or specific handling.
SORTING_MAP = {
    "Aerosols": "yellow",
    "Tin": "yellow",
    "Cardboard": "yellow",
    "Cellulose": "yellow",
    "Ceramic": "other",
    "Combined plastic": "yellow",
    "Container for household chemicals": "other",
    "Disposable tableware": "other",
    "Electronics": "other",
    "Foil": "yellow",
    "Furniture": "other",
    "Glass bottle": "glass",
    "Liquid": "other",
    "Milk bottle": "yellow",
    "Organic": "other",
    "Paper bag": "yellow",
    "Paper": "yellow",
    "Plastic bag": "yellow",
    "Plastic bottle": "yellow",
    "Plastic cup": "yellow",
    "Plastic toys": "other",
    "Printing industry": "yellow",
    "Scrap metal": "yellow",
    "Stretch film": "yellow",
    "Tetra pack": "yellow",
    "Textile": "other",
    "Ramen Cup": "other",
    "Food Packet": "other",
}
